import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={` antialiased`}
        >
        <ClerkProvider>
        <Header />

        <div className="flex min-h-screen ">
          <Sidebar />

          <div className="flex-1 bg-gray-100 scrollbar-hide overflow-y-auto p-4">{children}</div>
        </div>

      </ClerkProvider>
      </body>
    </html>
  );
}
